# Spatial Linear Model

The moving average constructions, creating spatially-autocorrelated random variables on stream networks, as developed in Chapter \@ref(ChapMA), are part of a larger strategy.  We use them as random errors in a spatial linear model.  

## Variance Components

The most general linear model that we consider is 

\begin{equation} 
\mathbf{Y} = \mathbf{X}\boldsymbol{\beta} + \mathbf{z}_u + \mathbf{z}_d +\mathbf{z}_e + \mathbf{W}_1\boldsymbol{\gamma}_1 + \ldots + \mathbf{W}_p\boldsymbol{\gamma}_p + \boldsymbol{\epsilon},
(#eq:spLinearModel)
\end{equation}

where $\mathbf{X}$ is a design matrix of fixed effects and $\boldsymbol{\beta}$ is a vector of parameters. The vector $\mathbf{z}_u$ contains spatially-autocorrelated random variables with a tail-up autocovariance, with $\textrm{var}(\mathbf{z}_u) = \sigma_u^2\mathbf{R}(\theta_r)$, where $\mathbf{R}(\theta_r)$ is a correlation matrix that depends on the range parameter $\theta_r$ as described in Section \@ref(TUModels). The vector $\mathbf{z}_d$ contains spatially-autocorrelated random variables with a tail-down autocovariance, $\textrm{var}(\mathbf{z}_d) = \sigma^2\mathbf{R}(\theta_r)$ as described in Section \@ref(TDModels). The vector $\mathbf{z}_e$ contains spatially-autocorrelated random variables with a Euclidean distance autocovariance, $\textrm{var}(\mathbf{z}_e) = \sigma_e^2\mathbf{R}(\theta_r)$ as described below. We can include non-spatial random effects, where $\mathbf{W}_k$ is a design matrix for random effects $\boldsymbol{\gamma}_k; k = 1,\ldots,p$ with $\textrm{var}(\boldsymbol{\gamma}_k)=\sigma^2_k\mathbf{I}$, and $\boldsymbol{\epsilon}$ contains independent random variables with
$\textrm{var}(\boldsymbol{\epsilon})=\sigma^2_0\mathbf{I}$.  When used for spatial prediction, this model is referred to as "universal"" kriging [@Le:Zide:stat:2006, pg. 107] , with "ordinary"" kriging being the special case where the design matrix $\mathbf{X}$ is a single column of ones [@Cres:stat:1993, pg. 119]. The most general covariance matrix we form is,
\begin{equation} 
  \begin{array}{c}
  \textrm{cov}(\mathbf{Y})=\boldsymbol{\Sigma}=\sigma_u^2\mathbf{R}(\theta_r) + 
  \sigma_d^2\mathbf{R}(\alpha_d) + \sigma_e^2\mathbf{R}(\alpha_e) + \\
  \sigma_1^2\mathbf{W}_1\mathbf{W}_1^\top + \ldots +
  \sigma_p^2\mathbf{W}_p\mathbf{W}_p^\top + \sigma_0^2\mathbf{I}.  
  \end{array}
(#eq:covStructure)
\end{equation} 

## Semivariograms

## Estimation

### Quasi Models

## Prediction

### Block Prediction

## Model Diagnostics
