--- 
title: "Spatial Statistics for Stream Networks"
author: "Jay M. Ver Hoef, Erin E. Peterson, Daniel J. Isaak"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib, jss984.bib, StatBibTex.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/SpatStatStreamNet
description: "Theory and software for spatial stream network models"
---

# Preface {-}

This book is a result of a long collaboration among the three of us. Our journey began at the _Holiday Inn Express on the River_ in Corvallis, Oregon, in August of 2003.  Jay was on a review committee for the [EPA STARMAP grant](https://cfpub.epa.gov/ncer_abstracts/index.cfm/fuseaction/display.abstractDetail/abstract/7821/report/0) to Oregon State University and Colorado State University.  Erin was working on her Ph.D. with Dave Theobald at Colorado State University, and they were doing research on the grant. Erin and Dave had presented some of their research.  Later, some of us who had travelled to Corvallis, were on the deck of the Holiday Inn overlooking the Willamette River, relaxing with a drink. Erin and Dave posed the question to Jay, "We would like to do kriging on streams, but use stream distance, rather than Euclidean distance.  Is it possible?"

Jay had used spatial moving averages in several previous publications to develop flexible spatial covariance models [@Barr:Ver:blac:1996], and for multivariable models [@Ver:Barr:cons:1998]. These models have also been called process convolutions [@Higd:proc:1998]. Jay had thought about the possibility of using these models on other topologies, even specifically for stream networks.  However, the task of getting data into a Geographical Information System (GIS), and extracting the necessary information, was daunting, and he had no one pressing him with a real application.  Erin and Dave provided the necessary push, and they had extensive GIS experience.  The collaboration was initiated.

About a year later, Jay taught a course on Spatial Statistics with Noel Cressie in Switzerland.  While soaking in the spa at Yverdon les Bains, Jay explained his work on stream networks to Noel.  Noel then worked with his colleagues, specifically Bronwyn Harch, and used these ideas for some research they had on stream networks in Australia.  The two seminal papers appeared [@Ver:Pete:Theo:spat:2006; @Cres:Frey:Harc:Smit:spat:2006].

After finishing her Ph.D., Erin was hired by Bronwyn Harch and worked at CSIRO in Brisbane, Australia.  Erin and Jay continued to collaborate on a series of papers [@Pete:Theo:Ver:supp:2007; @Pete:Ver:mixe:2010], and a full theory that included tail-up, tail-down, and Euclidean distance (classical geostatistical models) in a mixed model framework was presented as a discussion paper in a _Journal of the American Statistical Association_ paper [@Ver:Pete:Move:2010], with comments by @Cres:ODon:comm:2010 and @Sahu:comm:2010 and a rejoinder [@Ver:Pete:rejo:2010].

During this time, Dan learned of these methods, and contacted Erin and Jay.  Geostatistics has a long history of modeling air temperature, and Erin worked with Dan to produce a seminal paper on geostatistical modeling for stream temperature data [@Isaa:Luce:Riem:Nage:effe:2010].  It soon became apparent that in order for these models to be generally useful, software was needed to integrate GIS operations with statistical computing.

A watershed event occurred with a [working group at the National Center for Ecological Analysis and Synthesis (NCEAS)](https://www.nceas.ucsb.edu/featured/peterson) in Santa Barbara, with help from Deputy Director Stephanie Hampton and generous support from Chris Jordan, NOAA Fisheries.  Erin, Jay, and Dan realized that software, along with a broad base of users, was needed to really launch the methods. The NCEAS working group resulted in GIS software [@Pete:Ver:STAR:2014], **R** software, [@Ver:Pete:Clif:Shah:SSN:2014], and three applied papers show-casing the methods [@Pete:Ver:Isaa:stre:2013; @Isaa:Pete:Ver:Weng:Appl:2014; @Som:Mone:Ver:Zimm:Pete:spat:2014].

Since then, we have taught courses based on the methods and software at least once a year.  We continued the mapping of stream temperature throughout the western U.S. [@Isaa:Weng:Pete:Ver:norw:2017], and created layers for download and an interactive viewer

https://www.fs.fed.us/rm/boise/AWAE/projects/NorWeST.html

We also created a "National Stream Internet,"

https://www.fs.fed.us/rm/boise/AWAE/projects/NationalStreamInternet.html

where we have taken all of the streams in the continental U.S., starting with the [National Hydrography Database (NHD)](https://www.usgs.gov/core-science-systems/ngp/national-hydrography), and conditioned them so that they work with our models. 

We are trying to keep a [bibliography of applications](https://www.fs.fed.us/rm/boise/AWAE/projects/NationalStreamInternet/SSN_Bibliography.html). This book has grown from our desire to make these models as accessible as possible.  It has been a fun journey.  We enjoy working together, and making new colleagues along the way.

Jay, Erin, and Dan

## Software {-}

The **SSN** package can be installed from CRAN.  In an **R** terminal type

```{r eval=FALSE}
install.packages("SSN")
```

## Authors {-}

Jay Ver Hoef is a senior scientist and statistician for the Marine Mammal Lab, part of the Alaska Fisheries Science Center of NOAA Fisheries, U.S. Dept. of Commerce. He works for a U.S. Government research lab where he develops statistical methods and consults on a wide variety of topics related to marine mammals and stream networks. The Marine Mammal Lab is located in Seattle, Washington, although Jay lives in Fairbanks, Alaska.  His main statistical interests are in spatial statistics and Bayesian statistics, especially applied to ecological and environmental data.

Erin Peterson ...

Dan Isaak ...

## Acknowledgments {-}

We would like to thank...